from datetime import datetime

DATE_FORK = datetime(2011, 5, 19)

FOLDER_TO_SAVE_RESULT = "./storage"

PAST_IN_SIZE = 17
FUTURE_IN_SIZE = 20

P_OUT_SIZE = 30
HE_OUT_SIZE = 26

P_PAST_MLP_MODEL_PATH = ""
P_FUTURE_MLP_MODEL_PATH = ""
P_PAST_CNN_MODEL_PATH = ""
P_FUTURE_CNN_MODEL_PATH = ""
HE_PAST_MLP_MODEL_PATH = ""
HE_FUTURE_MLP_MODEL_PATH = ""
HE_PAST_CNN_MODEL_PATH = ""
HE_FUTURE_CNN_MODEL_PATH = ""

P_PAST_PROCESSORS_PATH = ""
P_FUTURE_PROCESSORS_PATH = ""
HE_PAST_PROCESSORS_PATH = ""
HE_FUTURE_PROCESSORS_PATH = ""
